import { Helmet } from "react-helmet-async";
import { Button } from "@/components/ui/button";
import { Link, useSearchParams } from "react-router-dom";
import { useKit } from "@/context/kit-context";
import KitItem from "@/components/kit/KitItem";
import KitSummary from "@/components/kit/KitSummary";
import ATSupplyCategories from "@/components/kit/ATSupplyCategories";
import CategoryProductSelector from "@/components/kit/CategoryProductSelector";
import { useMemo, useState, useEffect } from "react";
import { Product } from "@/lib/types";
import { Badge } from "@/components/ui/badge";
import { Sparkles } from "lucide-react";

type ViewMode = 'categories' | 'category-products';

const Build = () => {
  const canonical = typeof window !== "undefined" ? window.location.href : "";
  const { kit, addToKit, clearKit } = useKit();
  const [viewMode, setViewMode] = useState<ViewMode>('categories');
  const [selectedCategoryId, setSelectedCategoryId] = useState<string>('');
  const [searchParams, setSearchParams] = useSearchParams();
  const [isAIGenerated, setIsAIGenerated] = useState(false);

  const handleCategorySelect = (categoryId: string) => {
    setSelectedCategoryId(categoryId);
    setViewMode('category-products');
  };

  const handleBackToCategories = () => {
    setViewMode('categories');
    setSelectedCategoryId('');
  };

  // Handle deep link functionality for AI-generated kits
  useEffect(() => {
    const kitData = searchParams.get('kit');
    const aiGenerated = searchParams.get('ai') === 'true';
    
    if (kitData && aiGenerated) {
      try {
        const parsedKit = JSON.parse(decodeURIComponent(kitData));
        if (Array.isArray(parsedKit) && parsedKit.length > 0) {
          // Clear existing kit and add AI-generated items
          clearKit();
          parsedKit.forEach((item: any) => {
            addToKit({
              id: item.id || `ai-${Date.now()}-${Math.random()}`,
              name: item.name,
              brand: item.brand || 'Unknown',
              price: item.price || 0,
              imageUrl: item.image || '/placeholder-product.jpg',
              category: item.category || 'Other',
              description: item.description || '',
              features: item.features || [],
              materials: item.materials || [],
              // Remove sizes property since it's not defined in Product type
              // Remove colors property since it's not defined in Product type
              offers: item.offers || [{
                name: 'AI Generated',
                url: '#',
                price: item.price || 0,
                lastUpdated: new Date().toISOString()
              }]
            }, item.quantity || 1);
          });
          setIsAIGenerated(true);
          // Clear URL parameters after loading
          setSearchParams({});
        }
      } catch (error) {
        console.error('Failed to parse kit data from URL:', error);
      }
    }
  }, [searchParams, addToKit, clearKit, setSearchParams]);







  const grouped = useMemo(() => {
    const map = new Map<string, typeof kit>();
    kit.forEach(item => {
      if (!map.has(item.category)) map.set(item.category, []);
      map.get(item.category)!.push(item);
    });
    return Array.from(map.entries()).sort(([a],[b]) => a.localeCompare(b));
  }, [kit]);
  
  return (
    <main className="container mx-auto py-6 xs:py-8 sm:py-10 px-3 xs:px-4 sm:px-6">
      <Helmet>
        <title>AT Supply Finder</title>
        <meta name="description" content="Select tapes, bandages and more to create your athletic training kit and compare prices across vendors." />
        <link rel="canonical" href={canonical} />
      </Helmet>

      
      {/* AI-Generated Kit Indicator */}
      {isAIGenerated && kit.length > 0 && (
        <div className="mb-6 p-4 bg-gradient-to-r from-purple-50 to-blue-50 border border-purple-200 rounded-lg">
          <div className="flex items-center gap-2 mb-2">
            <Sparkles className="h-5 w-5 text-purple-600" />
            <Badge variant="secondary" className="bg-purple-100 text-purple-700">
              AI Generated Kit
            </Badge>
          </div>
          <p className="text-sm text-purple-700">
            This training kit was generated by our AI assistant based on your requirements. 
            You can modify quantities, remove items, or add more products as needed.
          </p>
        </div>
      )}

      <div className={kit.length > 0 ? "grid gap-4 xs:gap-6 lg:grid-cols-3" : ""}>
        <div className={kit.length > 0 ? "lg:col-span-2" : ""}>
          {viewMode === 'categories' ? (
            <ATSupplyCategories onCategorySelect={handleCategorySelect} />
          ) : viewMode === 'category-products' ? (
            <CategoryProductSelector 
              categoryId={selectedCategoryId} 
              onBack={handleBackToCategories} 
            />
          ) : kit.length > 0 ? (
            <div className="space-y-4 xs:space-y-6">
              {grouped.map(([category, items]) => (
                <div key={category} className="space-y-2 xs:space-y-3">
                  <h2 className="text-base xs:text-lg font-semibold">{category}</h2>
                  <div className="space-y-2">
                    {items.map(item => (
                      <KitItem key={item.id} item={item} />
                    ))}
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-8">
              <p className="text-muted-foreground mb-4">
                Start building your athletic training kit by selecting categories above.
              </p>
              <Button asChild variant="outline">
                <Link to="/catalog">Or browse all products</Link>
              </Button>
            </div>
          )}
        </div>
        {kit.length > 0 && (
          <div className="lg:col-span-1">
            <div className="lg:sticky lg:top-6">
              <KitSummary />
            </div>
          </div>
        )}
      </div>
    </main>
  );
};

export default Build;
