import React from 'react';
import { Badge } from '@/components/ui/badge';
import { Sparkles } from 'lucide-react';

interface AIKitIndicatorProps {
  isVisible: boolean;
}

export const AIKitIndicator: React.FC<AIKitIndicatorProps> = ({ isVisible }) => {
  if (!isVisible) return null;

  return (
    <div className="mb-6 p-4 bg-gradient-to-r from-purple-50 to-blue-50 border border-purple-200 rounded-lg">
      <div className="flex items-center gap-2 mb-2">
        <Sparkles className="h-5 w-5 text-accent" />
        <Badge variant="secondary" className="bg-accent/10 text-accent">
          AI Generated Kit
        </Badge>
      </div>
      <p className="text-sm text-accent">
        This training kit was generated by our AI assistant based on your requirements. 
        You can modify quantities, remove items, or add more products as needed.
      </p>
    </div>
  );
};

export default AIKitIndicator;